"plugins": [
        "react",
        "babel",
        "jest"
    ]
"extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:jest/recommended",
    "airbnb-base"
]
env:
  es6: true
  node: true
  jest: true
  browser: true

rules:
  no-console: 0
  import/extensions: 0